default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: emoji_mode_bot_development

test:
  <<: *default
  database: emoji_mode_bot_test

production:
  <<: *default
  database: emoji_mode_bot_production
